server.port=8080
spring.application.name=api-gateway

eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Routing configuration
spring.cloud.gateway.routes[0].id=student-management-server
spring.cloud.gateway.routes[0].uri=lb://student-management-server
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**, /login, /register, /complete-forced-account-update

spring.cloud.gateway.routes[1].id=notification-service
spring.cloud.gateway.routes[1].uri=lb://notification-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/notifications/**

# Global CORS configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=http://localhost:*, http://127.0.0.1:*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
