spring.application.name=student-management-server
server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:8082/SE2}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secret}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

jwt.secret=2XZCFnmx0gac60bn7LVsXtxpT36eCKJBGEbXg3luFuN
jwt.expiration=36000000

# Show SQL and format it
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Verbose logging for schema tool and SQL
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.tool.schema=TRACE
#logging.level.org.hibernate.orm.tooling=TRACE
