services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=SE2'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '8081:3306'
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/SE2?useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "myuser"
      SPRING_DATASOURCE_PASSWORD: "secret"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "create"
    ports:
      - '8080:8080'
    volumes:
      - file_uploads:/app/uploads
    restart: on-failure

volumes:
  file_uploads: